name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 安裝 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 安裝 Flutter
      - name: Install Flutter manually
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xz-utils
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz  # 使用最新版本的 Flutter
          tar xf flutter_linux_3.24.3-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH  # 將 Flutter 添加到全局 PATH
          flutter doctor
        shell: bash

      # 安裝 Flutter 依賴
      - name: Install dependencies
        run: flutter pub get
        shell: bash

      # 構建 APK
      - name: Build APK
        run: |
          flutter build apk --flavor client4Development --release
        shell: bash

      # 上傳 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: client4Development-apk
          path: build/app/outputs/flutter-apk/app-client4Development-release.apk
  build_ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          brew install --cask flutter
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
        shell: bash

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get
        shell: bash

      - name: Build IPA
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter build ios --release --no-codesign  # 未簽名的 IPA
        shell: bash

      - name: Upload IPA
        uses: actions/upload-artifact@v4  # 升級到 v4
        with:
          name: ipa
          path: build/ios/iphoneos/Runner.app  # 輸出 Runner.app
