name: Flutter CI

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  build_apk:
    runs-on: ubuntu-latest  # 使用 Ubuntu 環境來構建 APK
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
        shell: bash

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get
        shell: bash

      - name: Build APK
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter build apk --release
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ipa:
    runs-on: macos-latest  # 使用 macOS 環境來構建 IPA
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
        shell: bash

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get
        shell: bash

      - name: Build IPA
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter build ios --release --no-codesign  # 未簽名的 IPA
        shell: bash

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: build/ios/ipa/*.ipa
