name: Flutter CI

# 觸發條件
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # 檢出代碼
    - uses: actions/checkout@v2
    
    # 設置 Java 環境
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # 使用 subosito/flutter-action 來設置 Flutter SDK
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # 可以改成 'beta' 或具體版本
    
    # 取得 Flutter 依賴
    - run: flutter pub get
    
    # 檢查格式問題
    - run: flutter format --set-exit-if-changed .
    
    # 靜態分析
    - run: flutter analyze .
    
    # 運行測試
    - run: flutter test
    
    # 構建 APK 使用特定的 flavor
    - run: flutter build apk --flavor client4Development --release
    
    # 上傳生成的 APK
    - uses: actions/upload-artifact@v1
      with:
        name: client4Development-apk
        path: build/app/outputs/flutter-apk/app-development-release.apk
        
  build_ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          brew install --cask flutter
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
        shell: bash

      - name: Install dependencies
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter pub get
        shell: bash

      - name: Build IPA
        run: |
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter build ios --release --no-codesign  # 未簽名的 IPA
        shell: bash

      - name: Upload IPA
        uses: actions/upload-artifact@v4  # 升級到 v4
        with:
          name: ipa
          path: build/ios/iphoneos/Runner.app  # 輸出 Runner.app
