name: Flutter CI

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  build_apk:
    runs-on: ubuntu-latest  # 使用 Ubuntu 環境來構建 APK
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "export PATH=`pwd`/flutter/bin:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ipa:
    runs-on: macos-latest  # 使用 macOS 環境來構建 IPA
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "export PATH=`pwd`/flutter/bin:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ios --release --no-codesign  # 未簽名的 IPA

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: build/ios/ipa/*.ipa
